name: Lint
on: push
jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: actions/checkout@v1
      - name: Set Hello
        uses: ./actions/set-hello
        id: hello
      - name: Show message
        run: echo 'message ${{ steps.hello.outputs.coll_message }}'
