name: Lint
on: push
jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: actions/checkout@v1
      - name: Set Hello
        uses: ./actions/set-hello
        id: hello
      - name: Message
        run: echo 'MESSAGE!!! --- ${{ steps.hello.outputs.cool_message }}.'
