name: Lint
on: push
jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: actions/checkout@v1
      - name: Stylelint
        run: npx stylelint "**/*.(sa|sc|c)ss"
      - name: ESLint
        run: npx eslint "**/*.js" --format codeframe
        run: echo toJson(github)
      - name: Slack notification
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: ThisIsMyUsername # Optional. (defaults to webhook app)
          SLACK_CHANNEL: general # Optional. (defaults to webhook)
          SLACK_AVATAR: repository # Optional. can be (repository, sender, an URL) (defaults to webhook app avatar)
        uses: Ilshidur/action-slack@master
        with:
          args: '${{github.actor}} напушил вот сюда ${{github.repository}}' # Optional
