name: CI

on: [push]

jobs:
  my_cool_job:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    # - name: Use Node.js ${{ matrix.node-version }}
    #   uses: actions/setup-node@v1
    #   with:
    #     node-version: ${{ matrix.node-version }}
    # - run: npm install
    - name: Hello world action step
      uses: ./actions/hello
